[package]
name = "chess-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
chess-ai = { version = "0.1.0", path = "../chess-ai" }
chess-core = { version = "0.1.0", path = "../chess-core", features = ["all"] }
eframe = "0.31"
egui = "0.31"
egui_extras = { version = "0.31", features = ["image"] }
image = { version = "0.25", features = ["png"] }
resvg = "0.44"
usvg = "0.44"
rfd = "0.15"
arrayvec = "0.7.8"
tokio = { version = "1.53.1", features = ["sync", "rt-multi-thread", "macros"] }
flume = "0.12.0"
